import { useMutation } from "@tanstack/react-query";
import { useState } from "react";
import { Card } from "../components/Card";
import { apiPost } from "../utils/api";

type ReviewResponse = {
  ok: boolean;
  model: string;
  pdf_path: string;
  review_path: string;
  figures_reviewed: number;
};

export function ReviewPage() {
  const [pdfPath, setPdfPath] = useState<string>("");
  const [model, setModel] = useState<string>("gpt-4o-2024-11-20");

  const run = useMutation({
    mutationFn: () => apiPost<ReviewResponse>("/api/review", { pdf_path: pdfPath, model })
  });

  return (
    <div className="grid grid-cols-1 gap-4 lg:grid-cols-5">
      <Card
        title="Review"
        subtitle="VLM figure/caption/reference critique"
        className="lg:col-span-2"
        right={
          <button
            className="rounded-xl border border-sky-400/30 bg-sky-400/10 px-3 py-2 text-xs text-sky-200 hover:bg-sky-400/15"
            onClick={() => run.mutate()}
            disabled={run.isPending || !pdfPath}
          >
            {run.isPending ? "Running..." : "research_review"}
          </button>
        }
      >
        <div className="space-y-3">
          <label className="space-y-1">
            <div className="text-xs text-slate-300">pdf_path</div>
            <input
              className="w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-sm outline-none ring-sky-400/20 focus:ring-2"
              value={pdfPath}
              onChange={(e) => setPdfPath(e.target.value)}
              placeholder="Absolute path to PDF generated by a run"
            />
          </label>
          <label className="space-y-1">
            <div className="text-xs text-slate-300">model</div>
            <input
              className="w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-sm outline-none ring-sky-400/20 focus:ring-2"
              value={model}
              onChange={(e) => setModel(e.target.value)}
            />
          </label>
          {run.isError ? (
            <div className="rounded-xl border border-red-400/20 bg-red-500/10 p-3 text-sm text-red-200">
              {String(run.error)}
            </div>
          ) : null}
        </div>
      </Card>

      <Card title="Output" subtitle="Review artifact path" className="lg:col-span-3">
        {!run.data ? (
          <div className="text-sm text-slate-300">Provide a PDF path, then run review.</div>
        ) : (
          <div className="space-y-3 text-sm">
            <div className="rounded-xl border border-white/10 bg-white/5 p-3">
              <div className="text-xs text-slate-300">figures_reviewed</div>
              <div className="text-lg font-semibold">{run.data.figures_reviewed}</div>
            </div>
            <div className="rounded-xl border border-white/10 bg-white/5 p-3">
              <div className="text-xs text-slate-300">review_path</div>
              <div className="break-all text-slate-100">{run.data.review_path}</div>
            </div>
          </div>
        )}
      </Card>
    </div>
  );
}

